# Base image
FROM ubuntu:jammy

# Metadata
LABEL base.image="ubuntu:jammy" \
      dockerfile.version="2" \
      software="NCBI-Data" \
      software.version="v1.1" \
      description="Software for interacting with NCBI APIs" \
      maintainer="Jared Johnson" \
      maintainer.email="jared.johnson@doh.wa.gov"

# Avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

USER root

# Define user home explicitly
ENV HOME=/root

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
        wget \
        crun && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install NCBI Entrez Direct (EDirect)
RUN bash -c "$(wget -q https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/install-edirect.sh -O -)"

# Install NCBI Datasets CLI tools
RUN mkdir -p $HOME/bin && \
    wget -q https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets -O $HOME/bin/datasets && \
    wget -q https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/dataformat -O $HOME/bin/dataformat && \
    chmod +x $HOME/bin/datasets $HOME/bin/dataformat

# Set PATH
ENV PATH="$HOME/edirect:$HOME/bin:$PATH"
